var Add=4+4;
var Subtract=10-2;
var Divide=16/2;
var Multiply=4*2;
print(Add);
print(Subtract);
print(Divide);
print(Multiply);
console.log("Addition ="+" "+Add);
console.log("Subtraction="+" "+Subtract);
console.log("Division="+" "+Divide);
console.log("Multiplication"+" "+Multiply);